### ISSUE TITLE
pod install

### ISSUE THREAD

**Issue by alexnaldo** [pjchavarria/aozora-ios#161]
Hi,

I'm trying building to translate Aozora to Portuguese-BR but the 'pod install' doesn't work.

---------------------------------------------
Error loading the plugin `cocoapods-keys-1.7.0`.

LoadError - cannot load such file -- keyring
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:133:in `require'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:40:in `require'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-keys-1.7.0/lib/cocoapods_plugin.rb:1:in `<top (required)>'

I realdy installed 'cocoapods-keys-1.7.0' even with all permissions...

Any suggestion?

**Comment by sgript** [comment]
You should post this to the cocoapods-keys repo [issues](https://github.com/orta/cocoapods-keys).
